### ISSUE TITLE
testing for psfr() / sofr(): RLRT & anova.gam

### ISSUE THREAD

**Issue by fabian-s** [refunders/refund#23]
Matt wrote:

> How are the RLRTing functions going to interface with sofr?  sofr is going to be much too flexible for our RLR tests, right?  I believe both your method and mine require B-splines of a particular order with a particular order penalty.  Also, I don't think my approach can be extended to multiple functional predictors.  Also for mine the user needs to specify the special t2 basis.  They additionally need to specify REML fitting.  So rlrt.sofr is going to take a sofr fit as an argument and just throw an error if the user has not specified a sofr formula exactly in the form needed by our tests?

Bruce wrote:

> I agree with you that sofr will probably be too flexible for our RLR tests.  In terms of how testing will interface with sofr, I'm in a little bit of a holding pattern until sofr reveals itself a little more.  There is some discussion of just having mgcv::anova.gam() be the extent of testing.  Although, as I dig through the literature with which I used to be more familiar, it seems that there will be instances/models where mgcv::anova.gam() may not test the Hypothesis of interest.  

Matt wrote:

> I am rusty on the literature too.  This snippet from the anova.gam documentation suggests it would be a poor choice for the flm vs fgam test: For terms with a zero-dimensional null space (i.e. those
>      which can be penalized to zero) the approximation is often very
>      poor, and significance can be greatly overstated: i.e. p-values
>      are often substantially too low. This case applies to random effect terms

Bruce wrote:

> Do you have any take on the mgcv::anova.gam() vs. RLRsim kinds of testing?
> Do any of us know Simon Wood personally enough to contact him and see if he'd be interested in a collaboration ? Are we thinking of leaving testing of these models behind for a little bit?

Matt wrote:

> I guess we should implement what we can, make it as flexible as we can, and have a long warning and details section in the documentation. Potentially, if the user specifies something too complex we could still give them the results of anova.gam with a warning.

**Comment by fabian-s** [comment]
To me, the goal is not necessarily to get additional functionality if that means lots of additional implementation work.

I agree with Bruce that we'll have to wait a while until `psfr` takes shape. I agree with Matt re. warnings & documentation.

I can try to get Simon's input on this once we know what exactly it is we're trying to achieve.

**Comment by jgellar** [comment]
@swihart @mwmclean @jeff-goldsmith 
I'm guessing you guys haven't been thinking too much lately about updating your testing functions to work with the new `pfr`? Phil wants to push the next refund update to CRAN any day now, so my suggestion is to leave it for the next update. We still have `pfr_old()` and `fgam()` available for one more release, so if someone wants to perform these tests using the old interface they still can.

@mwmclean , what is the name of your testing function?

I agree with the above that, since both methods require a particular form for the fitted term, if the user tries to test a term that was not fit with that form then it should throw an error or warning.

I seem to remember that Simon Wood's test is only valid for models fit with a fixed smoothing parameter, so it would probably underestimate the p-values for the tests we want to make. But you guys would be more familiar with this than me.

**Comment by mwmclean** [comment]
I never implemented my test in refund.

**Comment by jgellar** [comment]
That explains why I wasn't able to find it.

If you built your function to work with `fgam` models, I imagine it should work pretty similarly with `pfr` models - you just need to do a check to make sure the model fits your criteria (one `af` term, fit with the `t2` basis, REML, etc). But then you would have had to do most of these checks with the old `fgam` as well, right?

**Comment by mwmclean** [comment]
I abandoned writing my test to work with fits from `fgam` mainly because I needed special constraints different than ones used by `mgcv`.  My code was written by hacking away at the old `gamm4::gamm4`  (now `gamm4:::gamm4.oldwork`) written to work with `lme4 < 1.0-0` and won't work with the current version of `lme4`.

**Comment by fabian-s** [comment]
closing this since nobody seems to be working on this.
