### ISSUE TITLE
ccb.fpc example fails

### ISSUE THREAD

**Issue by huangracer** [refunders/refund#36]
The ccb.fpc documentation example contains a call to fpca.sc which fails, I assume this is because that function is under active development, so testthat is setup to skip the test when the fpca.sc call fails

**Comment by jeff-goldsmith** [comment]
Just addressed this bug -- the issue was that the sparse data example includes some grid points for which no function is observed, resulting in missing values on the main diagonal of G0, the method-of-moments covariance estimator. This bug was fixed by using "na.rm = TRUE" in the sum where the measurement error variance is calculated.
