### ISSUE TITLE
defaults in fosr.perm

### ISSUE THREAD

**Issue by FelixGuenther** [refunders/refund#52]
Hi,
during my work with the refund package I discovered following bug/unclean setting of default values in the fosr.perm function:
Using it with option multi.sp = TRUE and method = "GLS" one automatically get's an error because of the default value prelim = 15.
The result of the preliminary permutation is a vector of length q consisting of the medians from the q different smoothing parameters out of the prelim permutations. This vector is handed over to the fosr function as lambda-argument for the main permutations. However fosr with method="GLS" only accepts scalar values or NULL for lambda.
The permutation test with "GLS" and multiple smoothing parameters works fine if prelim is manually set to 0.

**Comment by philreiss** [comment]
Thanks very much, Felix, for pointing out this problem. I've changed the default for prelim: it's now 0 if multi.sp=TRUE, 15 otherwise. (Note that multi.sp=TRUE works in fosr only if method="GLS"--at least currently.) Also, if multi.sp=TRUE and one sets prelim to >0, fosr.perm.fit will now issue an error message immediately rather than first running the preliminary permutations. Please let me know if this is adequate.
