### ISSUE TITLE
summary  does not work for pfr with af, pcr terms

### ISSUE THREAD

**Issue by fabian-s** [refunders/refund#58]
@mwmclean  @jgellar @jeff-goldsmith 

Running the code from `example(pfr)`,  I get:

```
> fit.af <- pfr(pasat ~ af(cca, Qtransform=TRUE, k=c(7,7)), data=DTI1)
> summary(fit.af)
Error in !fx : invalid argument type
```

and 

```
> fit.fpc <- pfr(pasat ~ fpc(cca), data=DTI1)
> summary(fit.fpc)
Error in S1[ind, ind] : subscript out of bounds
```

(on refundDevel_0.1-15; mgcv_1.8-7)

Both are triggered somewhere in  `summary.gam`, presumably because `af` and `fpc` don't set up the entries in `<pfr-object>$smooth` the way `mgcv` expects them to be set up. 

Not being able to run summary on these models sucks because it means we're losing much of the "free" accessibility/interpretability we want to achieve by using `mgcv` in the first place.

**Comment by jeff-goldsmith** [comment]
It's been a while since I looked at the fpc stuff -- do you have a sense for whether this is a quick fix or something more long-term? I agree that having this play nicely with summary.gam would be ideal...

@mwmcleanhttps://github.com/mwmclean @jgellarhttps://github.com/jgellar @jeff-goldsmithhttps://github.com/jeff-goldsmith

Running the code from example(pfr), I get:

> fit.af <- pfr(pasat ~ af(cca, Qtransform=TRUE, k=c(7,7)), data=DTI1)
> summary(fit.af)
> Error in !fx : invalid argument type

and

> fit.fpc <- pfr(pasat ~ fpc(cca), data=DTI1)
> summary(fit.fpc)
> Error in S1[ind, ind] : subscript out of bounds

(on refundDevel_0.1-15; mgcv_1.8-7)

Both are triggered somewhere in summary.gam, presumably because af and fpc don't set up the entries in <pfr-object>$smooth the way mgcv expects them to be set up.

Not being able to run summary on these models sucks because it means we're losing much of the "free" accessibility/interpretability we want to achieve by using mgcv in the first place.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/refunders/refund/issues/58

**Comment by fabian-s** [comment]
@jeff-goldsmith: This should not be too hard to fix, we just have to make sure everything is where mgcv expects it to be.

**Comment by jgellar** [comment]
Need to just run it in debug mode to see exactly what summary.gam() is looking for that we don't provide. Hopefully we can just provide this info as part of the pfr object. If not, then we would need to write our own summary() method, which would be considerably more work.

I can probably dig into this later in the week if nobody else can.

**Comment by fabian-s** [comment]
Thanks Jonathan! From the error message, I'm 90% sure it's just a matter of not saving the penalty matrix for `fpc`-terms in the expected location or the wrong form....

**Comment by jgellar** [comment]
f77ed4d3ce5abe448823c96ff39249d0e73b5bbd should fix the issue with `af` terms. For `fpc` terms though, I didn't do anything, and it's working just fine:

```
> data(DTI)
> DTI1 <- DTI[DTI$visit==1 & complete.cases(DTI),]
> fit.fpc <- pfr(pasat ~ fpc(cca), data=DTI1)
> summary(fit.fpc)

Family: gaussian 
Link function: identity 

...

R-sq.(adj) =  0.0761   Deviance explained = 8.94%
-REML =  253.6  Scale est. = 130.49    n = 66
```

@mwmclean and @jeff-goldsmith - could you try it out and see if you're having trouble with the `fpc` terms?

**Comment by fabian-s** [comment]
thanks, @jgellar. I can no longer reproduce either of the errors, weird, and sorry for the false alarm re `fpc()`. So the change that made it work was simply setting the class attribute of the smooth object differently? 

Why did you merge devel into master? That changed a lot of files in master in a lot of different places. I think it's usually better to leave the devel and master branches separate and let @huangracer do the merge whenever we're getting ready for a new release....? what do the others think?

**Comment by jeff-goldsmith** [comment]
@fabian-s, no worries about the false alarm -- always good to double check that things work the way we expect them to.

for what it's worth, i agree that our workflow should be to make changes in the devel branch and only update the master branch prior to a new release to CRAN. it seems the master branch is still passing, so we may not need to roll back the changes, but in the future maybe we can let @huangracer do the merging.

**Comment by jgellar** [comment]
I'm actually not sure when I merged devel into master. Maybe my repo wasn't up to date, and I had already addressed the `fpc` issue? I thought for this one change (which was just one line) I could do it on master, and save a step. But you're both right the proper way would be to make the changes on devel, and I'll do that in the future.

@fabian-s if you want the details:
The problem with `af` terms occurs when a quantile transformation is done (`QTransform = TRUE`), and a tensor product basis is used (the default). Recall that we defined the `dt` basis for "domain transformations" (originally for `pcox`, I believe, but I moved it over here). When `summary()` is called, there is a section where it checks whether or not the smooth is a tensor product basis, because the `$fixed` element of the smooth is labeled `$fx` if it's a tensor product. It didn't recognize the `dt` basis as being a tensor product basis, so it was looking for the wrong element name. Making the `dt_basis` class inherit from the `tensor.smooth` class fixes the issue, because `summary` knows that the object is really a tensor product smooth underneath. I _think_ this is a robust solution - but it gets kind of confusing when you're talking about domain transformations of tensor product bases.

**Comment by fabian-s** [comment]
@jgellar: it's perfectly fine to make bug fixes direct in master **AND devel**, esp. if they're as small as the one here, i.e. the first commit  https://github.com/refunders/refund/commit/2479aa3fe601856533a229e6cd638175e7557102 you pushed. Then you pushed a huge second one that merged devel into master, that's the one you referenced above. 
We just all have to be careful about what we push into the remote after doing things locally....

And thanks for the explanation....

@huangracer : can you check that everything is still up-to-par in `master` and roll back if not?

**Comment by jgellar** [comment]
That second commit was because I realized I had made this one change without pulling the most updated version of the repo (the master branch). So my workflow was the following:
1. Made one-line change on my (outdated) version of the master branch, and committed.
2. Pulled updated version of master branch
3. Pushed everything

I now worry - could this have erased some of the changes that were made between my outdated repo and the version I pulled?

**Comment by jgellar** [comment]
I had not updated the devel branch before with this change, I just did so. In the proper order this time (pull, make change, commit, then push).

**Comment by fabian-s** [comment]
> I now worry - could this have erased some of the changes that were made between my outdated repo and the version I pulled?

I don't think so, unless you got any conflict warnings and corrected them by manually overwriting your earlier changes or used something like git reset. Git checks the the local changes and warns you if the same parts of the code have been modified in the mean time in the remote, that's what it's for.

Thanks for fixing this, I hope I didn't come across too critical. I just worry about the state of the repo & the quality of the package, it's a little messy as it is so we really have to be careful.
